version: '3.11'

services:
  postgres:
    image: postgres:15
    volumes:
      - ${PWD}/bootstrap:/docker-entrypoint-initdb.d
      - ${PWD}/scripts:/sqlscripts
    ports:
       - 5432:5432
    environment:
      POSTGRES_PASSWORD:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_HOST_AUTH_METHOD: trust
